# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae931024860feb3b9e9ffb72b9df4c5cf32bd3cd38d8380fff48c2d652f0a5e9fff188130540f2786b8adc22db6181d9efa20f06cce4354cc90fd74cd16f4a5

test:
  secret_key_base: 89a89aa27f9fef2ee76aac84e29924b4a403cc95a0ec318374e90f84b23c0e9fb688751a8b2bbf188c8db40c24912fd8eed5b7a265b651e53fb7c029c12d8d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
